In [127]:
import pandas as pd
import numpy as np
from sklearn import model_selection
from sklearn import svm

In [128]:
tumor = pd.read_csv('https://raw.githubusercontent.com/AndrewH707/BrainTumorDetection/main/primary-tumor.csv')

In [129]:
column = tumor['degree-of-diffe'].fillna('base') #instead of dropping na, we can fill with a base
tumor['degree-of-diffe'] = column
tumor = tumor.dropna()

In [130]:
tumor['bone'].replace({True: 1, False: 0}, inplace=True)
tumor['bone-marrow'].replace({True: 1, False: 0}, inplace=True)
tumor['lung'].replace({True: 1, False: 0}, inplace=True)
tumor['pleura'].replace({True: 1, False: 0}, inplace=True)
tumor['peritoneum'].replace({True: 1, False: 0}, inplace=True)
tumor['liver'].replace({True: 1, False: 0}, inplace=True)
tumor['brain'].replace({True: 1, False: 0}, inplace=True)
tumor['skin'].replace({True: 1, False: 0}, inplace=True)
tumor['neck'].replace({True: 1, False: 0}, inplace=True)
tumor['supraclavicular'].replace({True: 1, False: 0}, inplace=True)
tumor['axillar'].replace({True: 1, False: 0}, inplace=True)
tumor['mediastinum'].replace({True: 1, False: 0}, inplace=True)
tumor['abdominal'].replace({True: 1, False: 0}, inplace=True)

In [131]:
(tumor.groupby('class').count()).get('age')

class
breast               17
cervix uteri          2
colon                13
corpus uteri          6
duoden and sm.int     1
esophagus             5
gallbladder          14
head and neck        10
kidney               20
liver                 7
lung                 43
ovary                17
pancreas             26
prostate              8
rectum                6
salivary glands       2
stomach              33
testis                1
thyroid              10
vagina                1
Name: age, dtype: int64

In [132]:
tumor['class'].replace({'bladder': 0, 'breast': 1, 'cervix uteri': 2, 'colon': 3, 'corpus uteri': 4, 'duoden and sm.int': 5, 'esophagus': 6, 'gallbladder': 7, 'head and neck': 8, 'kidney': 9, 'liver': 10, 'lung': 11, 'ovary': 12, 'pancreas': 13, 'prostate': 14, 'rectum': 15, 'salivary glands': 16, 'stomach': 17, 'testis': 18, 'thyroid': 19, 'vagina': 20}, inplace=True)

In [133]:
tumor

age     sex histologic-type degree-of-diffe  bone  bone-marrow  lung  \
2    30-59  female        adefalse            base     0            0     0   
3    30-59  female        adefalse            base     0            0     0   
4    30-59  female        adefalse            base     0            0     0   
5    30-59    male        adefalse            base     0            0     0   
6    30-59    male        adefalse            base     1            0     0   
..     ...     ...             ...             ...   ...          ...   ...   
303   >=60  female        adefalse            base     0            0     1   
305  30-59    male        adefalse            well     1            0     0   
306  30-59    male      epidermoid          poorly     1            0     0   
307  30-59  female        adefalse            well     0            0     0   
308  30-59  female        adefalse            base     1            0     1   

     pleura  peritoneum  liver  brain  skin  neck  supraclavicular  axillar  \
2         1           0      0      0     1     0                0        1   
3         0           1      0      0     0     0                0        0   
4         1           1      0      0     0     0                0        0   
5         0           0      1      0     0     0                0        0   
6         0           0      0      0     0     0                0        0   
..      ...         ...    ...    ...   ...   ...              ...      ...   
303       1           1      0      0     0     0                0        0   
305       0           0      0      0     0     1                1        0   
306       0           0      0      0     1     0                0        1   
307       1           1      0      0     0     0                0        0   
308       1           1      1      1     0     0                0        0   

     mediastinum  abdominal  class  
2              0          0      1  
3              0          0     12  
4              0          0     12  
5              0          0      3  
6              0          0     14  
..           ...        ...    ...  
303            0          1      4  
305            1          0     14  
306            0          0     11  
307            0          0     12  
308            0          1      7  

[242 rows x 18 columns]

In [134]:
tumor_features = ['bone', 'bone-marrow', 'lung', 'pleura', 'peritoneum', 'liver', 'brain', 'skin', 'neck', 'supraclavicular', 'axillar', 'mediastinum', 'abdominal']

In [135]:
X = tumor.loc[:,tumor_features].values
Y = tumor.loc[:,['class']]

In [156]:
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y, test_size = 0.3, random_state = 0)
clf_ob1 = svm.SVC(kernel= 'linear', C=1).fit(X_train, np.ravel(Y_train))
print(clf_ob1.score(X_test, Y_test))

0.352112676056338


In [157]:
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y, test_size = 0.2, random_state = 0)
clf_ob2 = svm.SVC(kernel= 'linear', C=1).fit(X_train, np.ravel(Y_train))
print(clf_ob2.score(X_test, Y_test))

0.3191489361702128


In [158]:
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y, test_size = 0.4, random_state = 0)
clf_ob3 = svm.SVC(kernel= 'linear', C=1).fit(X_train, np.ravel(Y_train))
print(clf_ob3.score(X_test, Y_test))

0.24468085106382978


In [159]:
# Remove classes that are too little
tumor_kfold = tumor[tumor['class'] != 20]
tumor_kfold = tumor_kfold[tumor_kfold['class'] != 18]
tumor_kfold = tumor_kfold[tumor_kfold['class'] != 16]
tumor_kfold = tumor_kfold[tumor_kfold['class'] != 5]
tumor_kfold = tumor_kfold[tumor_kfold['class'] != 2]

In [160]:
X = tumor_kfold.loc[:,tumor_features].values
Y = tumor_kfold.loc[:,['class']]

In [161]:
scores_res1 = model_selection.cross_val_score(clf_ob1, X, np.ravel(Y), cv=5)
scores_res1

array([0.38297872, 0.38297872, 0.36170213, 0.31914894, 0.23404255])

In [162]:
scores_res2 = model_selection.cross_val_score(clf_ob2, X, np.ravel(Y), cv=5)
scores_res2

array([0.38297872, 0.38297872, 0.36170213, 0.31914894, 0.23404255])

In [163]:
scores_res3 = model_selection.cross_val_score(clf_ob3, X, np.ravel(Y), cv=5)
scores_res3

array([0.38297872, 0.38297872, 0.36170213, 0.31914894, 0.23404255])